### PR TITLE
test: vaex.open using convert with unicode

### PR DESCRIPTION
**Pull request by maartenbreddels**
should expose #1183

### CODE REVIEW

**Comment by v1gnesh** [comment]
Think this is the culprit:
https://github.com/vaexio/vaex/blob/45de210d54f153c1898797ef06078f9a9fcdd6ec/packages/vaex-core/vaex/cache.py#L43

**Comment by maartenbreddels** [comment]
Thanks, would be great if you could check this actually.

**Comment by v1gnesh** [comment]
Thanks again; sure, will wait for release.

**Comment by maartenbreddels** [comment]
Fixed #1183

**Comment by v1gnesh** [comment]
> Thanks, would be great if you could check this actually.  

Upgraded as follows, and it works ok now.

```
>>> vaex.__version__
{'vaex': '4.0.0a9', 'vaex-core': '4.0.0a18', 'vaex-viz': '0.5.0.dev1', 'vaex-hdf5': '0.7.0a6', 'vaex-server': '0.4.0a1', 'vaex-astro': '0.8.0.dev1', 'vaex-jupyter': '0.6.0.dev1', 'vaex-ml': '0.11.0a5', 'vaex-arrow': '0.5.1'}
```

**Pull request merged**
