### PR TITLE
fix(core): give a better error msg on copying a dataframe with non-existing column

### LINKED ISSUE #221: Better handling when a non-existend column is used.
We need a better way to catch an error when a user makes a typo and queries a column that does not exist in a `DataFrame`. For example:
```
import vaex
ds = vaex.example()
ds[['x', 'xy']]   # gives a not so friendly error
```

On the other hand:
```
import vaex
ds = vaex.example()
ds['xy']   # gives a helpful error message
```

### PR DESCRIPTION
**Pull request by maartenbreddels**
Closes #221

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Instead of all names, we only hint at similar names:
image

**Comment by maartenbreddels** [comment]
Not all paths have this extra check, this is the normal error. Try with
[['sexx']], if you agree with what that looks like, we can then check at
other places as well.

(from mobile phone)

**Comment by JovanVeljanoski** [comment]
Ah yes you are right! So selecting a subset of a dataframe works
df[['pclas]] for example. This also works df['pclas', 'sexx'] (which is not supported by pandas for example. 

Is it possible for the same message to be shown when an expression is queried?
df['sexx'], i.e. to give the "Column or variable 'sexx' does not exist. ". Does not have to give the suggestions. Just for consistency.

**Comment by maartenbreddels** [comment]
> This also works df['pclas', 'sexx'] (which is not supported by pandas for example.

that is accidental, I don't think we should do/support that, do you?

**Comment by maartenbreddels** [comment]
like it? 
image

**Comment by JovanVeljanoski** [comment]
Stellar!

**Pull request merged**
