### PR TITLE
feat: support xarray format for quick aggregators (e.g. df.count(..))

### PR DESCRIPTION
**Pull request by maartenbreddels**
This is to be in line with #654 and the binby supporting xarray.
Example:
image

Also, this integrates well with plotly express' latest xarray support (cc @nicolaskruchten):
image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@JovanVeljanoski should format be renamed to `array_type='xarray'`?

**Comment by JovanVeljanoski** [comment]
> @JovanVeljanoski should format be renamed to `array_type='xarray'`?

Yes, i quite prefer this actually, great idea!

**Comment by maartenbreddels** [comment]
@JovanVeljanoski should we merge this, and we do docs separately, by pushing to the docs branch?

**Comment by JovanVeljanoski** [comment]
Let me test something out in the next 30 minutes or so, but it looks good. 

In any case we will do docs separately, so this will not be delayed due to that

**Pull request merged**
