### PR TITLE
Fix opening of Arrow non-stream files

### LINKED ISSUE #786: Can't open Arrow files
See https://github.com/vaexio/vaex/blob/2eaba353cc2f330933d6e9a4392b792bfad98183/packages/vaex-arrow/vaex_arrow/dataset.py#L26-L31.

It seems that `arrow` now throws an `OSError` when trying to open a non-stream file file with `open_stream`:

```
>>> pyarrow.ipc.open_stream("feat.arrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 146, in open_stream
    return RecordBatchStreamReader(source)
  File "/home/me/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 62, in __init__
    self._open(source)
  File "pyarrow/ipc.pxi", line 360, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: Invalid flatbuffers message.
```

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #786

r? @maartenbreddels

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Hi Laurențiu,

great, thanks for this!
However, I am a bit puzzled, looking at #404, this should already be tested, and the tests pass here locally (and on the CI). How did you create the two files in this PR? (for reference https://github.com/vaexio/vaex/pull/404/files is how we create a file and stream in the test).

**Comment by lnicola** [comment]
Actually, these files seem to "work", so I either didn't check properly, or messed something up. However, I still think my change is fine. The `ArrowInvalid` exception looks like:

    pyarrow.lib.ArrowInvalid: Expected to read 1330795073 metadata bytes, but only read 638

Which means that a part of the file was interpreted as a header, but the file was shorter.

So what happens if we make a larger file?

```python
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> import vaex
>>> 
>>> table = pa.Table.from_arrays([range(200000000)], names=["col1"])
>>> with pa.ipc.new_file("test.arrow", table.schema) as file:
...     file.write(table)
... 
>>> pa.ipc.open_stream("test.arrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grayshade/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 146, in open_stream
    return RecordBatchStreamReader(source)
  File "/home/grayshade/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 62, in __init__
    self._open(source)
  File "pyarrow/ipc.pxi", line 360, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: Invalid flatbuffers message.
>>> vaex.open("test.arrow")
ERROR:MainThread:vaex:error opening 'test.arrow'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grayshade/.local/lib/python3.8/site-packages/vaex/__init__.py", line 198, in open
    ds = vaex.file.open(path, *args, **kwargs)
  File "/home/grayshade/.local/lib/python3.8/site-packages/vaex/file/__init__.py", line 30, in open
    return opener.open(path, *args, **kwargs)
  File "/home/grayshade/.local/lib/python3.8/site-packages/vaex_arrow/opener.py", line 11, in open
    return DatasetArrow(path, *args, **kwargs)
  File "/home/grayshade/.local/lib/python3.8/site-packages/vaex_arrow/dataset.py", line 20, in __init__
    self._load()
  File "/home/grayshade/.local/lib/python3.8/site-packages/vaex_arrow/dataset.py", line 28, in _load
    reader = pa.ipc.open_stream(source)
  File "/home/grayshade/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 146, in open_stream
    return RecordBatchStreamReader(source)
  File "/home/grayshade/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 62, in __init__
    self._open(source)
  File "pyarrow/ipc.pxi", line 360, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: Invalid flatbuffers message.
```

So I think we should:

 - merge this change without a test, and/or
 - expose new `open_arrow_stream`, `open_arrow_file` methods

**Comment by maartenbreddels** [comment]
The most robust way would be to test if it starts with 'ARROW1' https://arrow.apache.org/docs/format/Columnar.html?highlight=arrow1#ipc-file-format, it might deserve an API in Arrow itself.

**Comment by lnicola** [comment]
Is `vaex.open` supposed to take paths? Because `pyarrow` accepts not only paths, but also files and streams.

**Comment by maartenbreddels** [comment]
path only, otherwise we cannot detect who should open the file.
I'm thinking however, to add more functions `vaex.arrow` in #517 or after that branch is merged, or `vaex.from_arrow_X`. What I like about the last approach, is that it is very tab completion friendly, and we could already add it now.

**Comment by maartenbreddels** [comment]
Thanks for starting this!

**Comment by lnicola** [comment]
Oof, thanks and sorry for dropping off the radar :disappointed:.

**Comment by maartenbreddels** [comment]
No worries, took me a while as well :)

**Pull request merged**
