### PR TITLE
Bump numpy~=1.26.4

### PR DESCRIPTION
**Pull request by ddelange**
fix flaky timeout on master by requiring recent numpy which has wheels available for musllinux_aarch64

### CODE REVIEW

**Comment by ddelange** [comment]
you're right, this PR doens't make sense in the current state.

on master there is only one failing wheel build: https://github.com/vaexio/vaex/actions/runs/10835977160/job/30068700570

due to `oldest-supported-numpy` selecting a version of numpy for which no wheels are available. building numpy from source under QEMU takes forever, so we're hitting the builtin github actions 6 hour timeout (which can't be increased)

**Comment by ddelange** [comment]
it's flaky: the `scheduled` run on master was successfull: https://github.com/vaexio/vaex/actions/runs/10841954610

**Comment by ddelange** [comment]
we could simplify our lives if we don't add support for musllinux_aarch64 wheels in the upcoming release. thoughts? 👍 👎

**Comment by maartenbreddels** [comment]
Only manylinux_aarch64 ? I'm fine with that!

**Comment by ddelange** [comment]
Closing in favour of https://github.com/vaexio/vaex/pull/2434

**Pull request closed without merging**
