### PR TITLE
Fix: datetime operations on virtual columns created via astype

### PR DESCRIPTION
**Pull request by JovanVeljanoski**
Exposed in #1582 

- [x] Unit-test
- [x] Make unit-test pass
- [ ] Review

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I don't get how this tests the issue in #1582, since we do not (or should not) convert to an arrow array. Did you test if the test fails without your code?

**Comment by JovanVeljanoski** [comment]
Yes of course it fails without the fix :) Hence the bug report of #1582 . You can try it!

So what happens is you start from a string, and that is handled by arrow. You cast that to datetime, but the string is then seen as an arrow Timestamp, and that breaks the `dt` stuff. So I cast it to pandas to make it work. 

Perhaps there is a better way of solving it, or maybe something with the `astype` is out of order, but I didn't want to touch that..

**Comment by maartenbreddels** [comment]
Yeah, I checked. I think it's becase we use pa.array(..) as default

**Comment by maartenbreddels** [comment]
Thanks !

**Pull request merged**
