### PR TITLE
✨ df.struct.flatten to get rid of arrow structs

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This is a split of from #2004 which need this feature

**Comment by JovanVeljanoski** [comment]
Should `df.struct.flatten()` also take a `columns` argument ? Maybe by default none (so apply to all struct cols), but maybe a user can choose a subset of cols to flatten?

**Comment by maartenbreddels** [comment]
Yes, that makes total sense.

**Comment by maartenbreddels** [comment]
OK, argument added, as well as a recursive flag.

**Review by JovanVeljanoski — APPROVED** [review]

**Pull request merged**
