### PR TITLE
Fix: more efficient check for value types in a column when creating a DataFrame

### PR DESCRIPTION
**Pull request by byaminov**
I noticed that when converting a Pandas data frame to Vaex it can take a lot of time. For example when working with NYC Taxi dataset and reading a CSV file of 7.5 million rows:
* `df = pd.read_csv("yellow_tripdata_2019-01.csv")` takes 12 seconds;
* `vaex.from_pandas(df)` takes on 1 minute 31 seconds on `master`, and only 3 seconds with the change from this PR.

I've traced the problem to the check `np.all(k == k)`. As I understand it's needed to filter out `np.NaN`s, and a `k == k` check should do the same but runs faster.

@maartenbreddels as you have more understanding of this code, please check if this change does not break anything. And I can add the benchmarks or performance tests described above somewhere to the repo, if you advise where.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This was introduced in #411 to solve #410, which allowed to have individual array elements (ndarray of type object) to be arrays as well. The comparison is a more general isnan comparison, but I'm not super happy with it either.
I fail to understand why it is so slow actually, I'll look into it a bit more.

**Comment by maartenbreddels** [comment]
Thanks, Bulat, this was a great catch. I've added the test that #411 was missing, and rewrote it slightly.

**Comment by byaminov** [comment]
@maartenbreddels cool thanks! The build seems to be [failing on `master`](https://travis-ci.org/vaexio/vaex/jobs/654470218?utm_medium=notification&utm_source=github_status) as well. Can you please try to reproduce on your Linux machine? Otherwise I can help later, by setting up some virtual linux. Seems like that test [is already skipped for a bunch of versions](https://github.com/vaexio/vaex/blob/4771c562b7bb8b2aaafd0beb1555dad12894aad8/tests/ml/ml_test.py#L247), so maybe we need to add another one...

**Comment by JovanVeljanoski** [comment]
> @maartenbreddels cool thanks! The build seems to be [failing on `master`](https://travis-ci.org/vaexio/vaex/jobs/654470218?utm_medium=notification&utm_source=github_status) as well. Can you please try to reproduce on your Linux machine? Otherwise I can help later, by setting up some virtual linux. Seems like that test [is already skipped for a bunch of versions](https://github.com/vaexio/vaex/blob/4771c562b7bb8b2aaafd0beb1555dad12894aad8/tests/ml/ml_test.py#L247), so maybe we need to add another one...

Hi @byaminov 

Yeah that is a problematic test.. the issue is on the numpy side so.. I'll take a look at it again. If it is `RobustScaler`  that is failing, feel free to ignore or complain to me.

**Comment by maartenbreddels** [comment]
Yes, there are 2 issues in CI, the robustscales, which has to do with the percentile_approx, which hints at a numpy issue, or an issue in vaex. That part will be refactored, so I don't want to spend too much time on it.
Also, because of a refactor, for the remote dataframe part, we sometimes run out of file handles. This is very recent, and actively thinking about it.

**Comment by maartenbreddels** [comment]
Great work, we should open an issue to convert the benchmarks to asv, and run them at least nightly, so we detect these regressions more easily.

**Comment by byaminov** [comment]
@maartenbreddels yes I like the idea of printing to an output file (did you mean CSV, otherwise what is asv?). IMO we can make it easy to measure and keep the output file committed for the history. Running them nightly can be quite flaky from my experience, but we can work on that as well.

For this PR - should we merge, as long as it's green?

**Comment by byaminov** [comment]
Created an issue #620 to track progress of setting up the automatic runs of the benchmarks with [ASV](https://asv.readthedocs.io/en/stable/).

**Comment by byaminov** [comment]
@maartenbreddels let me know if anything else is needed on this PR.

**Comment by JovanVeljanoski** [comment]
LGTM!

**Comment by maartenbreddels** [comment]
Looks very good, thanks a lot!

**Pull request merged**
