### PR TITLE
Fix pythonpackage.yml failing on macos-13

### PR DESCRIPTION
**Pull request by ddelange**
leftover from #2331, don't know why setup-graphviz started failing for macos-13 on master between the time of last commit in the PR and the time of merge. probably github team changed something in the runner image again...

### CODE REVIEW

**Comment by ddelange** [comment]
Switching to older xcode to avoid g++ compilation error:
```
In file included from src/strings.cpp:19:
In file included from vendor/boost/boost/xpressive/xpressive.hpp:18:
In file included from vendor/boost/boost/xpressive/xpressive_static.hpp:24:
In file included from vendor/boost/boost/xpressive/regex_primitives.hpp:22:
In file included from vendor/boost/boost/xpressive/detail/core/matchers.hpp:17:
In file included from vendor/boost/boost/xpressive/detail/core/matcher/alternate_end_matcher.hpp:20:
In file included from vendor/boost/boost/xpressive/detail/core/state.hpp:18:
In file included from vendor/boost/boost/xpressive/detail/core/access.hpp:21:
In file included from vendor/boost/boost/xpressive/match_results.hpp:42:
In file included from vendor/boost/boost/numeric/conversion/converter.hpp:13:
In file included from vendor/boost/boost/numeric/conversion/conversion_traits.hpp:13:
In file included from vendor/boost/boost/numeric/conversion/detail/conversion_traits.hpp:18:
In file included from vendor/boost/boost/numeric/conversion/detail/int_float_mixture.hpp:19:
In file included from vendor/boost/boost/mpl/integral_c.hpp:32:
vendor/boost/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion]
vendor/boost/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
#   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
```

**Comment by ddelange** [comment]
cc @maartenbreddels

**Comment by ddelange** [comment]
Found out why musllinux_aarch64 was taking so long: numpy has no such wheels available so they're being built from source, under QEMU :exploding_head: skipping them now: less minutes and less flakiness due to timeouts.

**Comment by ddelange** [comment]
@maartenbreddels green again

**Comment by maartenbreddels** [comment]
Thanks!

**Pull request merged**
