### PR TITLE
🐛 to_dask_array broke with most recent dask (2022.1.1)

### PR DESCRIPTION
**Pull request by maartenbreddels**
Due to https://github.com/dask/dask/pull/7417

### CODE REVIEW

**Comment by gjoseph92** [comment]
@maartenbreddels sorry about this change. Just curious, why not use the public [`da.from_array`](https://docs.dask.org/en/stable/generated/dask.array.from_array.html#dask.array.from_array) function instead of relying on these internals? You can specify your own `getitem`, `chunks`, and `meta` (and `name`), so from a quick skim I'd think it would work fine.

**Comment by ian-r-rose** [comment]
Sorry about this @maartenbreddels! I thought it was safe to change the function name, since (a) I viewed it as a private function (though Dask isn't very good about `_` prefixes or anything), and (b) the signature of the function changed anyways. I'd echo @gjoseph92's question: is there a reason to not use the more public (and stable) `da.from_array`?

**Comment by ludwigschwardt** [comment]
Hi @ian-r-rose and @gjoseph92, I hit the same snag in my library. I asked myself the same question, since it was so long ago 😅 It turned into quite an exploration, as documented in katdal/katdal#351, in case you are interested. Bottom line: I still like `getem` / `graph_from_arraylike` 😄

**Comment by maartenbreddels** [comment]
Good read @ludwigschwardt 

FYI: 2022.4.0 again break how we use dask, see https://github.com/vaexio/vaex/pull/2003
our getter isn't being called

**Comment by ludwigschwardt** [comment]
Thanks! I found that it helped to spell out the options, given that I haven't worked on this code in 4 years...

And thanks for the heads-up too.

The irony is that I converted back to `from_array` to be "future-proof" but then discovered that it only works because dask/dask#7417 / 2022.03.0 didn't optimise away my custom slices anymore, a [bug](https://github.com/dask/dask/issues/8753) for most but a feature for me :joy: I can get around this by specifying an explicit `getitem` that prevents optimisation, though.

I guessed that this behaviour will be short-lived, and here we are in 2022.04.0. Now my getter still works but my putter is bust 🙂

**Pull request merged**
