### PR TITLE
Fixing vaex.open for multipart parquet/arrow files

### PR DESCRIPTION
**Pull request by saikiran2603**
Fixes issue #1714 .
Changes 
1. During recursive call of vaex.open , fs and fs_options augments passed.
2. Added new key scheme for fs_options. If not passed , it will default to https.

### CODE REVIEW

**Review by maartenbreddels — APPROVED** [review]
Excellent work, thanks, this looks good to me.

**Comment by saikiran2603** [comment]
Hi @maartenbreddels  one of the checks seems to be stuck .. would it be possible to restart it ?

**Comment by maartenbreddels** [comment]
Yeah, I think your PR is good, some CI issue, don't worry!

@JovanVeljanoski https://github.com/vaexio/vaex/runs/4327718637?check_suite_focus=true fails again, I think the random draw sometimes misses some values, can you make it more robust?

**Comment by JovanVeljanoski** [comment]
Yeah I think this is ready to be merged. 

Yeah, i should fix that.. it is a massive time-sink tho.. maybe next week, especially if there is a new lockdown.

**Comment by maartenbreddels** [comment]
Thanks a lot @saikiran2603 !

**Pull request merged**
