### PR TITLE
fix(ml.ipynb): fixed a typo in the one hot encoder example

### PR DESCRIPTION
**Pull request by yetyetanotherusername**
Fixed a typo in the one hot encoder example

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks for your first contribution, I hope more will follow :)

PS: Note that the ML part is under construction.

**Comment by yetyetanotherusername** [comment]
Thanks again for your help on SO on getting data into vaex from pandas/pydata. This lib is amazing.

**Comment by maartenbreddels** [comment]
Thanks, really appreciate your kind words!
Which SO question was that? I can't link your username to it.

(from mobile phone)

**Comment by yetyetanotherusername** [comment]
https://stackoverflow.com/questions/59264275/convert-large-hdf5-dataset-written-via-pandas-pytables-to-vaex

**Comment by maartenbreddels** [comment]
Thanks, that Q and many similar questions will probably lead to some
improvements in helper functions and documentation, so thanks for that.

(from mobile phone)

**Pull request merged**
