### PR TITLE
Feature 608 - fix loading csv without header

### PR DESCRIPTION
**Pull request by mkst**
Felt like the right place to apply the fix, but let me know if you think it should be done somewhere else :)

fixes https://github.com/vaexio/vaex/issues/608

**edit:**
@maartenbreddels - anything I need to do here?

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Nice work Mark, and indeed that seems like a good place. 
The tests though have moved to the `tests/` directory, and we now use pytest for testing. Would you mind moving it, and getting rid of the class (just using functions is ok for pytest)? I suggest also a csv file at `tests/data/noheader.csv` without a header and a test at `tests/from_csv_test.py` to make sure this keeps working.

What do you think.

If unclear, me or Jovan can help.

**Comment by mkst** [comment]
@maartenbreddels, updated per your comments - hopefully good to go?

**Comment by maartenbreddels** [comment]
Took a bit long to get to this, thanks! I've changed it a bit, because vaex now support column names that are not valid identifiers. So now the column names can be '0' and '1' etc.

**Comment by mkst** [comment]
> Took a bit long to get to this, thanks! I've changed it a bit, because vaex now support column names that are not valid identifiers. So now the column names can be '0' and '1' etc.

No problem - had to go look at the original commit to refresh my memory! Thanks 👍

**Comment by maartenbreddels** [comment]
Thanks Mark, finally merged :)

**Pull request merged**
