### PR TITLE
chore: run benchmarks on dedicated hardware

### PR DESCRIPTION
**Pull request by byaminov**
Implement a script and instructions to run benchmarks as a cron job on dedicated hardware.
* Test all the new commits on `master`
* Test any commits on `bench*` branches in the base repo: to measure WIP performance improvements
* Publish results to the http://asv.vaex.io/
* Save results in the `gh-pages` repo for history

@maartenbreddels I have done some of the items from the [Initial setup of the machine](https://github.com/byaminov/vaex/blob/d0808e04415959df2659a467d894514264bc7064/benchmarks/README.rst#initial-setup-of-the-machine), but some you will have to do yourself, as you have permissions:
(2.) Add SSH key of `github` user as a [Deploy key](https://github.com/vaexio/vaex/settings/keys).
(3.) Clone the repo
(7.) Run ASV for the first time
(8.) Modify the cron job if you want a different cadence

TODO in this PR:
- [x] Have #672 merged to `master` and rebased this branch after that. Only last commit belongs to this change.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I prefer to use a separate repo `vaex-asv` for storing the data I can give you access to that as well.

**Comment by byaminov** [comment]
@maartenbreddels done rebasing. Please review.

**Comment by maartenbreddels** [comment]
I've modified it to use the vaex-asv repo, I think it's saver and clearer this way. Let me know if there is anything you don't like, other I'm happy to merge this.

First results are on http://asv.vaex.io/

**Comment by maartenbreddels** [comment]
Again a weird checkout issue, https://github.com/actions/checkout/issues/23 seems related, @JovanVeljanoski do you want to take a look?

**Pull request merged**
