### PR TITLE
Remove kapteyn dependency for vaex-astro

### PR DESCRIPTION
**Pull request by balbinot**
The kapteyn package is failing to build for python >= 3.7 due to some CYTHON issue in their WCSLib. That breaks the install of vaex-astro.

I propose removing the dependency on kapteyn by assuming static rotation matrices for the coordinate transformations, since the change of Equinox was not even implemented in the first place. 

PS: I changed the setup.py to allow force the --user flag to be passed to subpackages, but I am not sure how to remove it from the pull request.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Awesome! I will squash this PR in the end, so I just reverted it (=in the end the changes will be 1 commit).
Can you clean it up a bit, we can remove input and output, and remove the commenting of the import statement.

**Comment by maartenbreddels** [comment]
Really happy with this PR, this will in the end also allow the windows/appveyor CI to work again!

**Comment by balbinot** [comment]
> Awesome! I will squash this PR in the end, so I just reverted it (=in the end the changes will be 1 commit).
> Can you clean it up a bit, we can remove input and output, and remove the commenting of the import statement.

Sure, can I just make changes to my fork or I need a new PR?

**Comment by maartenbreddels** [comment]
You can continue making changes (pull first, since I've made changes to your branch :))

**Comment by balbinot** [comment]
Also tested coordinate conversion against astropy. 

Since astropy is a depdency, in the future using astropy standard transformations and units would add some flexibility. Not doing it right now, unless I need in the near future ;)

**Comment by maartenbreddels** [comment]
> Since astropy is a depdency

I would like to remove that actually, at least for vaex-core, but it's ok to be a test-dependency, so fine with that.

**Comment by maartenbreddels** [comment]
Thanks a lot!

**Pull request merged**
