### PR TITLE
fix appveyor by getting more deps from conda-forge

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks for the help, but the import should not have been top level. The py27 failure seems because arrow is not supported for python27 on windows it seems.

**Comment by DougRzz** [comment]
Apologies, my comment wasn't directly related to this issue. It was more of a general comment for Vaex in Windows with the fcntl module.

**Comment by maartenbreddels** [comment]
Ah ok, then I misunderstood. Hope to get windows on board again!

**Comment by maartenbreddels** [comment]
windows support back in by #117

**Pull request closed without merging**
