### PR TITLE
Fix: evaluation of a dataframe containing masked arrays

### PR DESCRIPTION
**Pull request by JovanVeljanoski**
When a dataframe (the whole dataframe, not an expression) is evaluated with the `.values` method, if a column contains masked values, those values will be realized as some numeric values (i think the masked values is filled with some large number). In the case of `numpy.ma.MaskedArray`, i expect the masked values to be "translated" to `np.nan`. This is what the unit-test assumes. 

This may be related to #639 although I am not quite sure. 

Checklist:
- [x] Unit-test that catches the issue
- [x] Making the unit-test pass 
- [ ] Manual testing

### CODE REVIEW

**Comment by maartenbreddels** [comment]
> i expect the masked values to be "translated" to `np.nan`

I would say, a masked array, not nan, since the underlying data is a masked array, would you agree?

**Comment by maartenbreddels** [comment]
Should we say `.values` gives a masked array, and we can change the semantics of np.array(df) later?

**Comment by JovanVeljanoski** [comment]
Yes that makes sense. 
So as we discussed elsewhere, is it possible to keep close (or follow exactly your proposal):
- `.values` will return the internal structure, if numpy array (masked) it will return a numpy array (masked if needed)
- to get a get a numpy array always we will keep to `np.array(df)`
- to get arrow array we will keep to `pa.array(df)`

**Comment by maartenbreddels** [comment]
We forgot the changelog :(

**Comment by maartenbreddels** [comment]
updated in master

**Pull request merged**
