### PR TITLE
fix: make vaex work with blake3 0.3

### LINKED ISSUE #1817: [BUG-REPORT] blake3 0.3.0 breaking changes
Pinning blake3 to 0.2.1 works as a fix for the error below.

**Description**

Vaex-core's dataset hash array functionality was broken by a recent update in blake3-py

```
tests/foo.py:96: in test_dataframe
    vaex_df = vaex.from_dict(matrix)
.venv/lib/python3.9/site-packages/vaex/__init__.py:310: in from_dict
    return vaex.from_arrays(**data)
.venv/lib/python3.9/site-packages/vaex/__init__.py:365: in from_arrays
    dataset = vaex.dataset.DatasetArrays(arrays)
.venv/lib/python3.9/site-packages/vaex/dataset.py:1287: in __init__
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
.venv/lib/python3.9/site-packages/vaex/dataset.py:1287: in <dictcomp>
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
.venv/lib/python3.9/site-packages/vaex/dataset.py:165: in hash_array
    hash_info = hash_array_data(ar)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ar = array([   0,    1,    2, ..., 9997, 9998, 9999])

    def hash_array_data(ar):
        # this function should stay consistent with all future versions
        # since this is the expensive part of the hashing
        if isinstance(ar, np.ndarray):
            ar = ar.ravel()
            if ar.dtype == np.object_:
                return {"type": "numpy", "data": str(uuid.uuid4()), "mask": None}
            if np.ma.isMaskedArray(ar):
                data_byte_ar = _to_bytes(ar.data)
                blake = blake3.blake3(data_byte_ar, multithreading=True)
                hash_data = {"type": "numpy", "data": blake.hexdigest(), "mask": None}
                if ar.mask is not True and ar.mask is not False and ar.mask is not np.True_ and ar.mask is not np.False_:
                    mask_byte_ar = _to_bytes(ar.mask)
                    blake = blake3.blake3(mask_byte_ar, multithreading=True)
                    hash_data["mask"] = blake.hexdigest()
                return hash_data
            else:
                try:
                    byte_ar = _to_bytes(ar)
                except ValueError:
                    byte_ar = ar.copy().view(np.uint8)
>               blake = blake3.blake3(byte_ar, multithreading=True)
E               TypeError: blake3.__new__() got an unexpected keyword argument 'multithreading'
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
    ```
    >>> import vaex; vaex.__version__
    {'vaex-core': '4.7.0', 'vaex-hdf5': '0.11.1'}
    ```
 - Vaex was installed via: pip 
 - OS: macos 12.0.1 (21A559)

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

### PR DESCRIPTION
**Pull request by anthonycorletti**
Closes #1817

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I prefer we make it either compatible with both, by checking the version number, or if the argument exists, or put in a minimum requirement, what do you think?

**Comment by maartenbreddels** [comment]
Looking at the blake3 readme, I think we should pass `max_threads=blake3.AUTO` now, if version >= 0.3 that is.

**Comment by anthonycorletti** [comment]
> Looking at the blake3 readme, I think we should pass `max_threads=blake3.AUTO` now, if version >= 0.3 that is.

makes sense!

so when the blake3 python client version is >=0.3 though, for cases where multithreading is set to false for earlier versions, max_threads should be set to one right?

**Comment by maartenbreddels** [comment]
I'm ok with auto

**Comment by maartenbreddels** [comment]
@anthonycorletti do you want me to fix this?

**Comment by anthonycorletti** [comment]
> @anthonycorletti do you want me to fix this?

hey @maartenbreddels, sure! that would be very helpful. im working on other things at the moment so i think you could get to this much faster than i could. 

thanks for your help!

**Comment by maartenbreddels** [comment]
Thanks @anthonycorletti for starting this!

**Pull request merged**
