### PR TITLE
feat(core, hdf5): support python keywords and invalid variable names

### PR DESCRIPTION
**Pull request by maartenbreddels**
Implemented using a df._column_aliases dict that will translate those names
when possible.
Note that it means that you cannot do:
```
df['class * 2']  # this expression cannot be parsed
```
but instead, you can do
```
df['class'] * 2  # this can use the aliasing
```
If for some reason you need to write an expression using strings, use:
```
expression_string = str(df['class']) + ' * 2'
```
Closes #253,  should also help with #369

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This is how it looks like in the notebook:
image

**Comment by aanilpala** [comment]
there seems to be issues with column names containing "+" as well. One hot encoder usually gives rises to such situations.

**Comment by aanilpala** [comment]
The workaround I've found and posted above won't work for some other non-python keywords than "+". Therefore, it is a very brittle solution as such characters are very typical in the text data that is passed to OHE. So, I had to come up with a better solution.

Turns out that all I needed to do was to get the column names with alias=False before passing them to the sklearn wrapper like in the following:

```
train_cols = [col for col in train.get_column_names(alias=False) if col != self.target_variable] 
target_col = self.target_variable
booster = train_lgbm_booster(hyper_params, train, valid=test, train_cols=train_cols, target_col=target_col)

vaex_lgbm_model = vaex.ml.sklearn.Predictor(
            features=train_cols,
            target=target_col,
            model=booster,
            prediction_name="pred")
```

**Comment by maartenbreddels** [comment]
Hi,

did you try with the latest alpha, i've fixed a bunch more corner cases. If that still doesn't work, could you open an issue with an example to reproduce it?

cheers,

Maarten

**Comment by aanilpala** [comment]
Hi, I haven't yet tried the alpha. I was waiting for the 4.0 release. Now that my problem is solved with get_column_names(alias=False), it is not an urgency anymore but I will try to see soon how the latest alpha behaves in a similar scenario.

**Comment by aanilpala** [comment]
I've tried this with 4.0.0a16. Unfortunately, it was not possible to run my pipeline smoothly without adding some additional logic that takes care of the non-python-expression column names. With the alias flag removed from get_column_names, the following code was necessary to be able to do state_set for OHE encoding (without using the transform from OHE but rather loading the state from another dataframe - .transform still worked but I am interested in applying vaex's implicit pipelines using state transform)

```
cols_to_rename = \
            [col for col in df.get_column_names() if col not in self.cat_feats and not valid_identifier(col)]

        for col in cols_to_rename:
            suggested_colname = re.sub('\W|^(?=\d)','_', col)
            df.rename(col, suggested_colname, unique=True)
```

**Comment by aanilpala** [comment]
I will try to add an example to reproduce it soon.

**Comment by aanilpala** [comment]
here: https://github.com/vaexio/vaex/issues/1200

**Pull request merged**
