### PR TITLE
Support for selections in vaex.agg functions

### PR DESCRIPTION
**Pull request by JovanVeljanoski**
With this PR we add `selection` arguments to the aggregators, i.e. `vaex.agg` methods. 
This will enable very flexible way of aggregating columns, for instance

```
df.groupby(df.x).agg({'y_mean_sel': vaex.agg.mean(df.y, selection='z > 10')})
```

In the above example, the `y_mean_sel` column will have the mean only of those values that pass the selection condition. This can be done per aggregation operation, offering great flexibility.

### CODE REVIEW

**Comment by ManuelZ** [comment]
Hi, what kind of syntax does selection supports?

**Comment by JovanVeljanoski** [comment]
Just the same as any other method that supports the `selection` kwarg. 

For example:

```
import vaex.ml
df = vaex.ml.datasets.load_titanic()
df.groupby('pclass').agg({'age_f': vaex.agg.mean('age', selection='sex == "female"'),
                          'age_m': vaex.agg.mean('age', selection=df.sex == "male"),
                          'age_f_surv': vaex.agg.mean('age', selection='(sex=="female") & (survived==True)'),
                          'age_m_surv': vaex.agg.mean('age', selection=((df.sex == "male") & (df.survived==True))),
                         })

```

And the output is 
image


Hope this makes sense!

**Comment by ManuelZ** [comment]
Oh nice thank you! Your last example helps a lot, I though that I only could write a string there.

**Comment by JovanVeljanoski** [comment]
You are welcome. Same goes for any other method that supports the `selection` argument (like plotting, `df.count`, `df.mean` etc)

**Comment by ManuelZ** [comment]
Another question. How can I create my own agg function? I need the mode, but I can't find it in [agg.html](https://vaex.readthedocs.io/en/latest/_modules/vaex/agg.html)

**Pull request merged**
